### ISSUE TITLE
Getting started guide specifies that you need to assign a security group, but req's for that group are not described

### ISSUE THREAD

**Issue by scealiontach** [blockchaintp/hyperledger-brooklyn-sawtooth#22]
Getting started guide specifies that you need to assign a security group, but req's for that group are not described.  What ports need to be opened, etc

**Comment by grkvlt** [comment]
The documentation here https://github.com/blockchaintp/hyperledger-brooklyn-sawtooth/blob/master/docs/aws-setup.md#create-an-aws-security-group gives the details for AWS. Other clouds have similar requirements.
